version: '2'

services:
  casamovel-db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - 5432:5432
    volumes:
      - C:/database:/var/lib/postgresql/data
